name: Go Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'

    - name: Run tests in arrays
      working-directory: ./arrays
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in helloworld
      working-directory: ./helloworld
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in integers
      working-directory: ./integers
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in iteration
      working-directory: ./iteration
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in pointers
      working-directory: ./pointers
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in structs
      working-directory: ./structs
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in maps
      working-directory: ./maps
      run: |
        go mod tidy
        go test -v ./...


    - name: Run tests in di
      working-directory: ./di
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in mocks
      working-directory: ./mocks
      run: |
        go mod tidy
        go test -v ./...

    - name: Run tests in concurrency
      working-directory: ./concurrency
      run: |
        go mod tidy
        go test -v ./...
